(function () {
  const PALETTE = {
    k: '#1a1a1a', w: '#ffffff', o: '#f0713d', y: '#f5d93d',
    g: '#9dc24c', e: '#e8e8e8', b: '#4a90d9', p: '#f2b5a0',
    s: '#43434a', c: '#c08f52',
    x: '#217346', d: '#2b579a', m: '#1d63ed', v: '#0065a9', q: '#fe315d',
    a: '#ea4335', u: '#a9c7e8', f: '#eef4fb', r: '#c94867', n: '#2f3b52',
    j: '#1db954', z: '#7d5ba6',
    i: '#1679a7', t: '#147efb', l: '#0a66c2', h: '#e24329',
  };
  const MAPS = {
    // Smoky — Neko Atsume regular cat, くろねこさん "Black Cat" (solid black, yellow eyes)
    cat: [
      '..k..........k..',
      '.ksk........ksk.',
      '.kssk......kssk.',
      '.kssskkkkkksssk.',
      'kssssssssssssssk',
      'kssyyssssssyyssk',
      'kssyyssssssyyssk',
      'kssssssskssssssk',
      '.kssssssssssssk.',
      '.kssssssssssssk.',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      '.kssssssssssssk.',
      '..kkkkkkkkkkkk..',
    ],
    // ekspresi Smoky — baris mata/mulut divariasikan dari peta dasar
    catHappy: [
      '..k..........k..',
      '.ksk........ksk.',
      '.kssk......kssk.',
      '.kssskkkkkksssk.',
      'kssssssssssssssk',
      'kssyyssssssyyssk',
      'ksoyyssssssyyosk',
      'kssssskskskssssk',
      '.kssssssssssssk.',
      '.kssssssssssssk.',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      '.kssssssssssssk.',
      '..kkkkkkkkkkkk..',
    ],
    catAnnoyed: [
      '..k..........k..',
      '.ksk........ksk.',
      '.kssk......kssk.',
      '.kssskkkkkksssk.',
      'kssssssssssssbsk',
      'kssssssssssssssk',
      'kssyyssssssyyssk',
      'kssssskkkssssssk',
      '.kssssssssssssk.',
      '.kssssssssssssk.',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      '.kssssssssssssk.',
      '..kkkkkkkkkkkk..',
    ],
    catSleep: [
      '..k..........k..',
      '.ksk........ksk.',
      '.kssk......kssk.',
      '.kssskkkkkksssk.',
      'kssssssssssssssk',
      'ksskksssssskkssk',
      'kssssssssssssssk',
      'kssssssskssssssk',
      '.kssssssssssssk.',
      '.kssssssssssssk.',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      'kssssssssssssssk',
      '.kssssssssssssk.',
      '..kkkkkkkkkkkk..',
    ],
    // Smoky ngintip dari kardus (homage pose Neko Atsume "cardboard house")
    catBox: [
      '....k........k......',
      '...ksk......ksk.....',
      '...kssk....kssk.....',
      '...kssskkkkksssk....',
      '..kssssssssssssssk..',
      '..kssyyssssssyyssk..',
      '..kssyyssssssyyssk..',
      '..kssssssskssssssk..',
      'kkkkkkkkkkkkkkkkkkkk',
      'kcccccccccccccccccck',
      'kccccggggcccccccccck',
      'kcccccccccccccccccck',
      'kcccccccccccccccccck',
      'kcccccccccccccccccck',
      'kkkkkkkkkkkkkkkkkkkk',
      '....................',
    ],
    fileDoc: [
      '..kkkkkkkkkkk...',
      '..kwwwwwwwwkk...',
      '..kwwwwwwwwkwk..',
      '..kwwwwwwwwkkk..',
      '..kwwwwwwwwwwk..',
      '..kwkkkkwwwwwk..',
      '..kwwwwwwwwwwk..',
      '..kwkkkkkkwwwk..',
      '..kwwwwwwwwwwk..',
      '..kwkkkkkkkwwk..',
      '..kwwwwwwwwwwk..',
      '..kwkkkkwwwwwk..',
      '..kwwwwwwwwwwk..',
      '..kkkkkkkkkkkk..',
      '................',
      '................',
    ],
    // ikon aplikasi untuk app windows
    excel: [
      'kkkkkkkkkkkk',
      'kxxxxxxxxxxk',
      'kxwxxxxxxwxk',
      'kxxwxxxxwxxk',
      'kxxxwxxwxxxk',
      'kxxxxwwxxxxk',
      'kxxxxwwxxxxk',
      'kxxxwxxwxxxk',
      'kxxwxxxxwxxk',
      'kxwxxxxxxwxk',
      'kxxxxxxxxxxk',
      'kkkkkkkkkkkk',
    ],
    word: [
      'kkkkkkkkkkkk',
      'kddddddddddk',
      'kdwdddwdddwk',
      'kdwdddwdddwk',
      'kdwdddwdddwk',
      'kddwdwdwdwdk',
      'kddwdwdwdwdk',
      'kdddwdddwddk',
      'kdddwdddwddk',
      'kddddddddddk',
      'kddddddddddk',
      'kkkkkkkkkkkk',
    ],
    // Notion: huruf N hitam di atas kartu putih
    notion: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwkkkkkkkkkwwwwwwk',
      'kwwkkwwwwwwwwkkwwwwk',
      'kwwkkwwwwkkkkkkkwwwk',
      'kwwkkkkkkkkwwwwkwwwk',
      'kwwkkkwwwwwwwwwkwwwk',
      'kwwkkkwkkkwwkwwkwwwk',
      'kwwkkkwwkkkwkwwkwwwk',
      'kwwkkkwwkkkwkwwkwwwk',
      'kwwkkkwwkwkkkwwkwwwk',
      'kwwkkkwwkwkkkwwkwwwk',
      'kwwkkkwwkwwkkwwkwwwk',
      'kwwwkkwwkwwwwwwkwwwk',
      'kwwwkkwwwwwwwkkkwwwk',
      'kwwwwkkkkkkkkkkwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    // VS Code: pita putih (chevron + bar kanan) di atas kotak biru
    vscode: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kvvvvvvvvvvvvvvvvvvk',
      'kvvvvvvvvvvvvvvvvvvk',
      'kvvvvvvvvvvvwwwvvvvk',
      'kvvvvvvvvvvwwwwwwvvk',
      'kvvvvvvvvvwwwwwwwvvk',
      'kvvvwvvvvwwwwwwwwvvk',
      'kvvwwwvvwwwwwwwwwvvk',
      'kvvvwwwwwwwvvwwwwvvk',
      'kvvvvwwwwwvvvwwwwvvk',
      'kvvvvwwwwwvvvwwwwvvk',
      'kvvvwwwwwwwvvwwwwvvk',
      'kvvwwwvvwwwwwwwwwvvk',
      'kvvvwvvvvwwwwwwwwvvk',
      'kvvvvvvvvvwwwwwwwvvk',
      'kvvvvvvvvvvwwwwwwvvk',
      'kvvvvvvvvvvvwwwvvvvk',
      'kvvvvvvvvvvvvvvvvvvk',
      'kvvvvvvvvvvvvvvvvvvk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    idea: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkwwkkkwwwwkwwwwkkk',
      'kkkwwwkwwwwwkwwwwkkk',
      'kkkwwwkwwwwwkwwwwkkk',
      'kkkwwwkwwwwwkwwwwkkk',
      'kkkwwwkkwkkkkwwwwkkk',
      'kkkwwkkkwwkkwwwwwkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkwwkkkkwwwwwwwwkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkwwwwwwwwwwwwwwkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    docker: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmwwmmmmmmmmk',
      'kmmmmmmmmwwmmmmmmmmk',
      'kmmmmmwwwwwmmmwmmmmk',
      'kmmmwwwwwwwwmwwwmmmk',
      'kmmmwwwwwwwwwwwwwmmk',
      'kmmwwwwwwwwwwwwmmmmk',
      'kmmwwwwwwwwwwwmmmmmk',
      'kmmwwwwwwwwwwwmmmmmk',
      'kmmmwwwwwwwwwmmmmmmk',
      'kmmmmwwwwwwmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kmmmmmmmmmmmmmmmmmmk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    // Wireshark: sirip hiu biru di atas air
    wireshark: [
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      'kwwwwwwwwwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwwwwwwwwwk',
      'kwwwiiiiiiiiiiiiiiiiiiiiwwwk',
      'kwwiiwwwwwwwwwwwwwwwwwwiiwwk',
      'kwwiwwwwwwwwwwwwwwwwwwwwiwwk',
      'kwwiwwwwwwwwwwwwwwwwwwwwiwwk',
      'kwwiwwwwwwwwwwwwwwwwwwwwiwwk',
      'kwwiwwwwwwwwwwwiiiiwwwwwiwwk',
      'kwwiwwwwwwwwwiiiwwiwwwwwiwwk',
      'kwwiwwwwwwwwiiwwwiiwwwwwiwwk',
      'kwwiwwwwwwwiiwwwwiwwwwwwiwwk',
      'kwwiwwwwwwwiwwwwwiwwwwwwiwwk',
      'kwwiwwwwwwiwwwwwwiwwwwwwiwwk',
      'kwwiwwwwwwiwwwwwwiwwwwwwiwwk',
      'kwwiwwwwwiwwwwwwwiwwwwwwiwwk',
      'kwwiwwwwwiwwwwwwwiiwwwwwiwwk',
      'kwwiwwwwwiwwwwwwwwiwwwwwiwwk',
      'kwwiiiiiiiwwwwwwwwiiiiiiiwwk',
      'kwwiiiiiiwwwwwwwwwwiiiiiiwwk',
      'kwwiwwwwwwwwwwwwwwwwwwwwiwwk',
      'kwwiwwwwwwwwwwwwwwwwwwwwiwwk',
      'kwwiwwwwwwwwwwwwwwwwwwwwiwwk',
      'kwwiiwwwwwwwwwwwwwwwwwwiiwwk',
      'kwwwiiiiiiiiiiiiiiiiiiiiwwwk',
      'kwwwwwwwwwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ],
    n8n: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkwwwkkk',
      'kkkkkkkkkkkwwwwkwkkk',
      'kkkwwkkwwkkwkkkwkkkk',
      'kkkwkwwwkwwkkkkkkkkk',
      'kkkwwkkwwkkwkwwkkkkk',
      'kkkkkkkkkkkwwkkwkkkk',
      'kkkkkkkkkkkkkwwkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    gitlab: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwhwwwwwwwwhwwwwk',
      'kwwwwhwwwwwwwwhwwwwk',
      'kwwwhhhwwwwwwhhhwwwk',
      'kwwwhhhwwwwwwhhhwwwk',
      'kwwwhhhhhhhhhhhhwwwk',
      'kwwhhhhhhhhhhhhhhwwk',
      'kwwhhhhhhhhhhhhhhwwk',
      'kwwhhhhhhhhhhhhhhwwk',
      'kwwhhhhhhhhhhhhhhwwk',
      'kwwwhhhhhhhhhhhhwwwk',
      'kwwwwhhhhhhhhhhwwwwk',
      'kwwwwwwhhhhhhwwwwwwk',
      'kwwwwwwwhhhhwwwwwwwk',
      'kwwwwwwwwhhwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    // Xcode: palu putih di atas kotak biru
    xcode: [
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
      'kttttttttttttttttttttttttttttttk',
      'kttttttttttttttttttttttttttttttk',
      'kttttttttttttttttttttttttttttttk',
      'ktttttttttttttttwwwwwwtttttttttk',
      'kttttttttttttttttttwwwwwtttttttk',
      'ktttttwwwwwwwwwwttttwwwwwttttttk',
      'kttttwwttwwwwwwwwwwtwwwwwwwwtttk',
      'ktttwwtwwwwwwwwwwwwttwwwwwwwtttk',
      'ktttwtwwwwwwwwwwwwwtwwwttwwttttk',
      'ktttwtwwwwwwwttttwttwwttttwttttk',
      'ktttwtwwwwwwwttttwtwwttwtttttttk',
      'ktttwtwwwwwwwwttwttwwtwwwwtttttk',
      'ktttwtwwwwwwwtttwtwwttwwwwtttttk',
      'ktttwtwwwwwwwttwtwwwtwwwwwtttttk',
      'ktttwtwwwwwwttwwtwwttwwwwwtttttk',
      'ktttwtwwwwwwttwtwwwtwwwwwwtttttk',
      'ktttwtwwwwwttwwtwwttwwwwwwtttttk',
      'ktttwtwwtttttttwwwttttwwwwtttttk',
      'ktttwtwwtttttttwwtttttwwwwtttttk',
      'ktttwtwwwttwwtwwwtttwwwwwwtttttk',
      'ktttwtwwwttwtwwwttwttwwwwwtttttk',
      'ktttwtwwwtwwtwwwtwwttwwwwwtttttk',
      'ktttwtwwwwwtwwwwtwwwwwwtwttttttk',
      'ktttwwtwwwttwwwttwwwwwttwttttttk',
      'kttttwwttttwwwwtttttttwwtttttttk',
      'kttttttwwttwwwttwwwwwwwttttttttk',
      'kttttttttttwwwtttttttttttttttttk',
      'kttttttttttttttttttttttttttttttk',
      'kttttttttttttttttttttttttttttttk',
      'kttttttttttttttttttttttttttttttk',
      'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    ],
    // avatar GitHub Dikau: kucing abu bertopi biru "WOLF"
    catCap: [
      '..kkkkkkkkkkk...',
      '.kbbbbbbbbbbbk..',
      '.kbbbbbbbbbbbbk.',
      'kbbbbbbbbbbbbbbk',
      'keeeeeeeeeeeeeek',
      'keekkeeeeeekkeek',
      'keekkeeeeeekkeek',
      'keeeeeeepeeeeeek',
      '.keeeeeeeeeeeek.',
      '.keeeeeeeeeeeek.',
      'keeeeeeeeeeeeeek',
      'keeeeeeeeeeeeeek',
      'keeeeeeeeeeeeeek',
      '.keeeeeeeeeeeek.',
      '..kkkkkkkkkkkk..',
      '................',
    ],
    // Smoky ber-outfit Tyler, the Creator era CMIYGL: ushanka biru + suit pastel
    catTyler: [
      '..kkkkkkkkkkkk..',
      '.kfuufuufuufufk.',
      'kfuufuufuufuufuk',
      'kuffuffuffuffuuk',
      'kfkkkkkkkkkkkkfk',
      'kfksssssssssskfk',
      'kfksyyssssyyskfk',
      'kfksyyssssyyskfk',
      '.kksssssksssskk.',
      '..kssskkkksssk..',
      '...kssssssssk...',
      '..kkkkkkkkkkkk..',
      '.kuukwwwwkkuuk..',
      'kuuukwkkwkuuuuk.',
      'kuuukwwwwkuuuuk.',
      'kuuuukkkkuuuuuk.',
      'kkkkkkkkkkkkkkk.',
      '................',
    ],
    // tanda tangan "dikau" — cursive pixel; dua titik di atas 'u' = mata,
    // lengkung 'u' jadi senyum
    sig: [
      '............................',
      '....k....k..................',
      '....k....k............k.k...',
      '....k..k.k............k.k...',
      '....k....k..................',
      '.kk.k..k.k..k...kk.k.k...k..',
      'k..kk..k.k.k...k..kk.k...k..',
      'k..kk..k.kk....k..kk.k...k..',
      'k..kk..k.k.k...k..kk.k...k..',
      '.kk.k..k.k..k...kk.k..kkk...',
      '............................',
    ],
    // ---- wardrobe Smoky: overlay 16x16 sejajar peta kucing ----
    wHatCap: [
      '................',
      '.....kkkkkk.....',
      '...kkbbbbbbkk...',
      '..kbbbbbbbbbbk..',
      'kkbbbbbbbbbbbbkk',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wHatUshanka: [
      '................',
      '....ffuuffuu....',
      '..kfuuffuuffuk..',
      '..kuffuuffuufk..',
      'kkuffuuffuuffukk',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wHatCrown: [
      '................',
      '..k..k..k..k..k.',
      '..kyykyykyykyyk.',
      '..kyyyyyyyyyyyk.',
      '..kkkkkkkkkkkkk.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wHatBeanie: [
      '................',
      '....kkkkkkkk....',
      '..kkooooooookk..',
      '.kkoooooooooook.',
      'kkooooooooooookk',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wFitSuit: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.kuukwwwwkkuuk..',
      'kuuukwwwwkuuuuk.',
      'kuuuukkkkuuuuuk.',
      '................',
    ],
    wFitHoodie: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.nnnnnnnnnnnnnn.',
      'nnwnnnnnnnnnnwnn',
      'nnwnnnnnnnnnnwnn',
      '................',
    ],
    wFitScarf: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.rrrrrrrrrrrrrr.',
      'krrrrrrrrrrrrrrk',
      '.krrrrrrrrrrrrk.',
      '..kkrrrrrrrrkk..',
    ],
    wAccGlasses: [
      '................',
      '................',
      '................',
      '................',
      '.kkkkkkkkkkkkkk.',
      '.kwwwwkkkkwwwwk.',
      '.kwwwwk..kwwwwk.',
      '..kkkk....kkkk..',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wAccHeadphones: [
      '................',
      '................',
      '...kkkkkkkkkk...',
      '..k..........k..',
      'krrk........krrk',
      'krrk........krrk',
      'krrk........krrk',
      '.kk..........kk.',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wAccBowtie: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '....krrkkrrk....',
      '....krrkkrrk....',
      '................',
    ],
    // seragam khusus untuk penghuni apartemen di tab About
    wFitPmi: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.aaawwwwwwwwaaa.',
      '.aaawwwaawwwaaa.',
      '.aaawwaaaawwaaa.',
      '.aaawwwaawwwaaa.',
      '..aaawwwwwwaaa..',
      '................',
    ],
    wHatHardHat: [
      '................',
      '.....kkkkkk.....',
      '...kkwwaawwkk...',
      '..kwwwaaaawwwk..',
      'kkeeeeeeeeeeeekk',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    wFitVolunteer: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.nnnnnuuuunnnnn.',
      '.nnnnnnuunnnnnn.',
      '.nnnnnnnnnnnnnn.',
      '.nnnnnnnnnnnnnn.',
      '..nnnnnnnnnnnn..',
      '................',
    ],
    wFitBlazerUpi: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.aaaakwwwwkaaaa.',
      '.aaaakwwwwkaaaa.',
      '.aaaakwwwwkaaaa.',
      '.aaaakwwwwkaaaa.',
      '..aaaawwwwaaaa..',
      '................',
    ],
    wFitShirtTie: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.uwuuwwwwwwuuwu.',
      '.uwuuwudduwuuwu.',
      '.uwuuwudduwuuwu.',
      '.uwuuwudduwuuwu.',
      '..wuuwudduwuuw..',
      '................',
    ],
    gmail: [
      'kkkkkkkkkkkkkkkkkkkk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwaaawwwwwwwwaaawwk',
      'kwwaaaawwwwwwaaaawwk',
      'kwwaaaaawwwwaaaaawwk',
      'kwwaaaaaawwaaaaaawwk',
      'kwwaaaaaaaaaaaaaawwk',
      'kwwaaaaaaaaaaaaaawwk',
      'kwwaaawwaaaawwaaawwk',
      'kwwaaawwwaawwwaaawwk',
      'kwwaaawwwwwwwwaaawwk',
      'kwwaaawwwwwwwwaaawwk',
      'kwwaaawwwwwwwwaaawwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kwwwwwwwwwwwwwwwwwwk',
      'kkkkkkkkkkkkkkkkkkkk',
    ],
    // glyph activity bar VS Code (digambar terang utk latar gelap)
    gFiles: [
      '............',
      '..eeee......',
      '..e..e......',
      '..e..eeee...',
      '..e..e..e...',
      '..eeee..e...',
      '....e...e...',
      '....e...e...',
      '....eeeee...',
      '............',
      '............',
      '............',
    ],
    gSearch: [
      '............',
      '...eeee.....',
      '..e....e....',
      '..e....e....',
      '..e....e....',
      '...eeee.....',
      '......ee....',
      '.......ee...',
      '........ee..',
      '............',
      '............',
      '............',
    ],
    gScm: [
      '..ee........',
      '..ee........',
      '...e........',
      '...e....ee..',
      '...e....ee..',
      '...ee...e...',
      '....ee.ee...',
      '.....eee....',
      '......e.....',
      '......ee....',
      '......ee....',
      '............',
    ],
    gExt: [
      '......eee...',
      '..eee.eee...',
      '..eee.......',
      '............',
      '..eee.eee...',
      '..eee.eee...',
      '............',
      '............',
      '............',
      '............',
      '............',
      '............',
    ],
    cap: [
      '............',
      '.....kk.....',
      '...kkkkkk...',
      '.kkkkkkkkkk.',
      'kkkkkkkkkkkk',
      '.kkkkkkkkkk.',
      '...kssssk.y.',
      '...kssssk.y.',
      '....kkkk..y.',
      '..........y.',
      '..........k.',
      '............',
    ],
    case: [
      '............',
      '....kkkk....',
      '....k..k....',
      '.kkkkkkkkkk.',
      '.kcccccccck.',
      '.kcccyyccck.',
      '.kcccccccck.',
      '.kcccccccck.',
      '.kkkkkkkkkk.',
      '............',
      '............',
      '............',
    ],
    trophy: [
      '............',
      '.kkkkkkkkkk.',
      '.kyyyyyyyyk.',
      'kkyyyyyyyykk',
      'k.kyyyyyyk.k',
      '..kyyyyyyk..',
      '...kyyyyk...',
      '....kyyk....',
      '.....kk.....',
      '....kyyk....',
      '...kkkkkk...',
      '............',
    ],
    fish: [
      '............',
      '............',
      '.kkkkkk.....',
      'kwwkwwwk.kk.',
      'kwwwwwwwkkk.',
      'kwwwwwwwk.k.',
      '.kkkkkk..k..',
      '............',
      '............',
      '............',
      '............',
      '............',
    ],
    brush: [
      '..kkkkkk....',
      '.kwwwwwwk...',
      '.kwwwwwwk...',
      '..kkkkkk....',
      '....kk......',
      '...kyyk.....',
      '...kyyk.....',
      '...kyyk.....',
      '...kyyk.....',
      '....kk......',
      '............',
      '............',
    ],
    ball: [
      '............',
      '...kkkk.....',
      '..kooook....',
      '.kowoooook..',
      '.koooooook..',
      '.koooooook..',
      '..kooook....',
      '...kkkk.....',
      '............',
      '............',
      '............',
      '............',
    ],
    // Finder-style two-tone face
    about: [
      '.kkkkkkkkkk.',
      'keeeeebbbbbk',
      'keeeeebbbbbk',
      'keekeebbkbbk',
      'keekeebbkbbk',
      'keeeeebbbbbk',
      'kekeeebbbkbk',
      'keekkkkkkbbk',
      'keeeeebbbbbk',
      'keeeeebbbbbk',
      '.kkkkkkkkkk.',
      '............',
    ],
    folder: [
      '............',
      'kkkkk.......',
      'kyyyykkkkkk.',
      'kyyyyyyyyyk.',
      'kkkkkkkkkkkk',
      'kyyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kyyyyyyyyyyk',
      'kkkkkkkkkkkk',
      '............',
    ],
    chip: [
      '..k..k..k...',
      '.kkkkkkkkk..',
      'kkgggggggkk.',
      '.kggkkkggk..',
      'kkgkgggkgkk.',
      '.kgkgggkgk..',
      'kkgkgggkgkk.',
      '.kggkkkggk..',
      'kkgggggggkk.',
      '.kkkkkkkkk..',
      '..k..k..k...',
      '............',
    ],
    mail: [
      '............',
      'kkkkkkkkkkkk',
      'kwwwwwwwwwwk',
      'kkwwwwwwwwkk',
      'kwkwwwwwwkwk',
      'kwwkwwwwkwwk',
      'kwwwkkkkwwwk',
      'kwwwwwwwwwwk',
      'kwwwwwwwwwwk',
      'kkkkkkkkkkkk',
      '............',
      '............',
    ],
    term: [
      'kkkkkkkkkkkk',
      'kkkkkkkkkkkk',
      'kgkkkkkkkkgk',
      'kkgkkkkkkkkk',
      'kkkgkkkkkkkk',
      'kkgkkkkkkkkk',
      'kgkkkkkkkkgk',
      'kkkkkggggkkk',
      'kkkkkkkkkkkk',
      'kkkkkkkkkkkk',
      '............',
      '............',
    ],
  };
  // ikon yang dibuat Dikau sendiri lewat pixelit — dipakai sebagai gambar,
  // bukan peta pixel, karena hasilnya lebih bagus dari gambar tangan
  const IMAGES = {
    github: 'assets/icons/brand/github.png',
    linkedin: 'assets/icons/brand/linkedin.png',
    spotify: 'assets/icons/brand/spotify.png',
  };
  function render(name, scale = 1) {
    if (!IMAGES[name] && !MAPS[name]) {
      // jangan sampai satu nama salah mematikan seluruh proses render
      console.warn('PixelArt: peta tidak dikenal:', name);
      return document.createElement('span');
    }
    if (IMAGES[name]) {
      const img = document.createElement('img');
      img.src = IMAGES[name];
      img.alt = '';
      img.className = 'px-img';
      img.width = 16 * scale;
      img.height = 16 * scale;
      return img;
    }
    const map = MAPS[name];
    const NS = 'http://www.w3.org/2000/svg';
    const svg = document.createElementNS(NS, 'svg');
    const h = map.length, w = map[0].length;
    svg.setAttribute('viewBox', `0 0 ${w} ${h}`);
    svg.setAttribute('width', w * scale);
    svg.setAttribute('height', h * scale);
    svg.setAttribute('shape-rendering', 'crispEdges');
    svg.setAttribute('aria-hidden', 'true');
    map.forEach((row, y) => {
      [...row].forEach((ch, x) => {
        if (ch === '.') return;
        const r = document.createElementNS(NS, 'rect');
        r.setAttribute('x', x); r.setAttribute('y', y);
        r.setAttribute('width', 1); r.setAttribute('height', 1);
        r.setAttribute('fill', PALETTE[ch] || '#000');
        svg.appendChild(r);
      });
    });
    return svg;
  }
  // renderStack: gambar beberapa peta berlapis (untuk wardrobe Smoky).
  // Layer wajib berdimensi sama dengan peta dasar; yang tidak cocok dilewati.
  function renderStack(names, scale = 1) {
    const list = names.filter((n) => n && MAPS[n]);
    if (!list.length) return render('cat', scale);
    const base = MAPS[list[0]];
    const NS = 'http://www.w3.org/2000/svg';
    const svg = document.createElementNS(NS, 'svg');
    const h = base.length, w = base[0].length;
    svg.setAttribute('viewBox', `0 0 ${w} ${h}`);
    svg.setAttribute('width', w * scale);
    svg.setAttribute('height', h * scale);
    svg.setAttribute('shape-rendering', 'crispEdges');
    svg.setAttribute('aria-hidden', 'true');
    list.forEach((name) => {
      const map = MAPS[name];
      if (map.length !== h || map[0].length !== w) return;
      map.forEach((row, y) => {
        [...row].forEach((ch, x) => {
          if (ch === '.') return;
          const r = document.createElementNS(NS, 'rect');
          r.setAttribute('x', x); r.setAttribute('y', y);
          r.setAttribute('width', 1); r.setAttribute('height', 1);
          r.setAttribute('fill', PALETTE[ch] || '#000');
          svg.appendChild(r);
        });
      });
    });
    return svg;
  }

  window.PixelArt = { render, renderStack, MAPS };
})();
